CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6)
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    type VARCHAR(255)
);

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    type VARCHAR(255),
    balance NUMERIC(38, 2),
    app_user_id BIGINT NOT NULL,
    CONSTRAINT fk_accounts_user
        FOREIGN KEY (app_user_id) REFERENCES app_user(id)
);

CREATE TABLE budget (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    app_user_id BIGINT NOT NULL,
    month VARCHAR(255),
    limit_amount NUMERIC(38, 2),
    CONSTRAINT fk_budget_category
        FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_budget_user
        FOREIGN KEY (app_user_id) REFERENCES app_user(id)
);

CREATE TABLE financial_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    description VARCHAR(255),
    amount NUMERIC(38, 2),
    type VARCHAR(255),
    transaction_date_time TIMESTAMP(6),
    CONSTRAINT fk_transaction_category
        FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_transaction_account
        FOREIGN KEY (account_id) REFERENCES accounts(id)
);
